In [15]:
import numpy as np

In [17]:
labels = [b'NO',b'DH',b'SL']
data = np.loadtxt('column_3C.dat',converters={6: lambda s: labels.index(s)})
data.shape

(310, 7)

In [18]:
data[0]

array([ 63.03,  22.55,  39.61,  40.48,  98.67,  -0.25,   1.  ])

In [20]:
# Separate labels from features
x = data[:,:6]
y = data[:,6]

In [21]:
x[0]

array([ 63.03,  22.55,  39.61,  40.48,  98.67,  -0.25])

In [23]:
# split on train and test
tr_idx = list(range(0,20))+list(range(40,188))+list(range(230,310))
ts_idx = list(range(20,40))+list(range(188,230))

tr_x = x[tr_idx,:]
ts_x = x[ts_idx,:]
tr_y = y[tr_idx]
ts_y = y[ts_idx]

tr_x[0]

array([ 63.03,  22.55,  39.61,  40.48,  98.67,  -0.25])

## Nearest Neighbor Classification with L2 distance
In this exercise we will build a nearest neighbor classifier based on L2 (*Euclidean*) distance.

<font color="magenta">**For you to do:**</font> Write a function, **NN_L2**, which takes as input the training data (`trainx` and `trainy`) and the test points (`testx`) and predicts labels for these test points using 1-NN classification. These labels should be returned in a `numpy` array with one entry per test point. For **NN_L2**, the L2 norm should be used as the distance metric.

In [24]:
def get_dist(x,y):
    dist = np.sum(np.square(x-y))
    return dist
get_dist(x[0],x[1])

1346.1031999999998

In [55]:
def get_NN(x):
    return np.argmin([get_dist(tr_x[i,],x) for i in range(len(tr_y))])

In [56]:
get_NN(ts_x[0])

170

In [57]:
tr_x[170]

array([  43.12,   13.82,   40.35,   29.3 ,  128.52,    0.97])

In [58]:
ts_x[0]

array([  43.92,   14.18,   37.83,   29.74,  134.46,    6.45])

In [60]:
def get_NN_ind(x):
    return  tr_y[get_NN(x)]

In [62]:
get_NN_ind(ts_x)

2.0

In [63]:
def NN_L2(tr_x,tr_y,ts_x):
    predictions = [get_NN_ind(ts_x[i,]) for i in range(len(ts_y))]
    
    return np.array(predictions)

In [66]:
testy_L2 = NN_L2(tr_x, tr_y, ts_x)

assert( type( testy_L2).__name__ == 'ndarray' )
assert( len(testy_L2) == 62 ) 
assert( np.all( testy_L2[50:60] == [ 0.,  0.,  0.,  0.,  2.,  0.,  2.,  0.,  0.,  0.] )  )
assert( np.all( testy_L2[0:10] == [ 0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.] ) )

In [64]:
# test function 
testy_L2 = NN_L2(tr_x, tr_y, ts_x)
print( type( testy_L2) )
print( len(testy_L2) )
print( testy_L2[40:50] )

<class 'numpy.ndarray'>
62
[ 2.  2.  1.  0.  0.  0.  0.  0.  0.  0.]


# 3. Nearest neighbor classification with L1 distance

We now compute nearest neighbors using the L1 distance (sometimes called *Manhattan Distance*).

<font color="magenta">**For you to do:**</font> Write a function, **NN_L1**, which again takes as input the arrays `trainx`, `trainy`, and `testx`, and predicts labels for the test points using 1-nearest neighbor classification. For **NN_L1**, the L1 distance metric should be used. As before, the predicted labels should be returned in a `numpy` array with one entry per test point.

Notice that **NN_L1** and **NN_L2** may well produce different predictions on the test set.

In [67]:
def l1_dist(x,y):
    return np.sum(np.abs(x-y))

In [68]:
def get_idx(x):
    return np.argmin([l1_dist(x,tr_x[i,]) for i in range(len(tr_y))])

In [70]:
def l1_Classifier(x):
    index = get_idx(x)
    return tr_y[index]

In [71]:
def NN_L1(tr_x,tr_y,ts_x):
    prediction = [l1_Classifier(ts_x[i,]) for i in range(len(ts_y))]
    return np.array(prediction)

In [73]:
testy_L1 = NN_L1(tr_x, tr_y, ts_x)
testy_L2 = NN_L2(tr_x, tr_y, ts_x)

assert( type( testy_L1).__name__ == 'ndarray' )
assert( len(testy_L1) == 62 ) 
assert( not all(testy_L1 == testy_L2) )
assert( all(testy_L1[50:60]== [ 0.,  2.,  1.,  0.,  2.,  0.,  0.,  0.,  0.,  0.]) )
assert( all( testy_L1[0:10] == [ 0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.]) )

In [76]:
print(tr_x[0],ts_x[0],sep='\n')

[ 63.03  22.55  39.61  40.48  98.67  -0.25]
[  43.92   14.18   37.83   29.74  134.46    6.45]


In [77]:
l1_dist(tr_x[0],ts_x[0])

82.490000000000009

In [78]:
get_idx(ts_x[0])

170

In [79]:
tr_x[170]

array([  43.12,   13.82,   40.35,   29.3 ,  128.52,    0.97])

In [80]:
l1_dist(tr_x[170],ts_x[0])

15.540000000000003

In [84]:
l1_Classifier(ts_x[0])

0.0

In [85]:
tr_y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [86]:
[l1_dist(x,tr_x[i,]) for i in range(len(tr_y))]

[30860.669999999998,
 34206.370000000003,
 29845.169999999998,
 29607.43,
 30662.529999999999,
 35549.790000000001,
 26937.249999999996,
 33965.790000000001,
 28902.41,
 39647.730000000003,
 32395.510000000002,
 43442.410000000003,
 28297.189999999999,
 28925.169999999998,
 27128.549999999999,
 29514.449999999997,
 27356.330000000002,
 37392.209999999992,
 33592.989999999998,
 32475.569999999996,
 41626.210000000006,
 30724.41,
 28261.550000000003,
 28165.509999999998,
 28041.529999999999,
 29612.610000000004,
 29988.809999999998,
 34427.809999999998,
 33535.370000000003,
 35862.209999999999,
 28111.389999999999,
 37030.350000000006,
 33944.349999999999,
 37070.849999999999,
 35337.410000000003,
 31286.630000000001,
 31811.889999999999,
 28715.169999999998,
 33301.449999999997,
 28440.09,
 43096.790000000001,
 55420.610000000008,
 30809.350000000006,
 31044.030000000002,
 34373.770000000004,
 35185.75,
 30567.91,
 41584.850000000006,
 28323.650000000001,
 33669.990000000005,
 28607.690

In [88]:
np.argmin([l1_dist(x,tr_x[i,]) for i in range(len(tr_y))])

224

In [89]:
len([l1_dist(x,tr_x[i,]) for i in range(len(tr_y))])

248

# 4. Test errors and the confusion matrix
Let's see if the L1 and L2 distance functions yield different error rates for nearest neighbor classification of the test data.

In [91]:
def error_rate(testy, testy_fit):
    return float(sum(testy!=testy_fit))/len(testy) 

print("Error rate of NN_L1: ", error_rate(ts_y,testy_L1) )
print("Error rate of NN_L2: ", error_rate(ts_y,testy_L2) )

Error rate of NN_L1:  0.22580645161290322
Error rate of NN_L2:  0.20967741935483872


In [94]:
print(ts_y)
testy_L1

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.
  2.  2.  2.  2.  2.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.]


array([ 0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,
        1.,  1.,  1.,  1.,  0.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,
        1.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  1.,  0.])

In [96]:
print(len(ts_y),len(testy_L1))

62 62
